INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('1453837736','CreateSpace');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B00364K6YW','A&E HOME VIDEO');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0440245915','Dell');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B0019NG7GI','Warner Home Video');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0061743526','Harper');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0783225857','Universal Studios');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0312195265','St. Martin`s Griffin');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B000MGB6N2','Metro-Goldwyn-Mayer');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0307387178','Anchor');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B001GMH8SI','Paramount');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0618002251','Houghton Mifflin');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B003TT2X6I','New Line Home Video');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B003TT2X6S','New Line Home Video');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0307474275','Anchor');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B000I2J2XG','Sony Pictures');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B002O5M4SU','Sony Pictures');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0425240339','Berkley');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B001AII4SQ','Paramount');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('0446692638','Grand Central Publishing');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('B00003CXUY','Paramount');

INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z783225857', 'Universal Studios');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z00003CXUY', 'Paramount');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z000I2J2XG', 'Sony Pictures');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z000MGB6N2', 'Metro-Goldwyn-Mayer');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z0019NG7GI', 'Warner Home Video');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z001AII4SQ', 'Paramount');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z001GMH8SI', 'Paramount');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z002O5M4SU', 'Sony Pictures');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z00364K6YW', 'A&E HOME VIDEO');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z003TT2X6I', 'New Line Home Video');
INSERT INTO `onlinebookstore`.`published_by` (ID,name) VALUES ('Z003TT2X6S', 'New Line Home Video');