INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Jane Austen','1453837736');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Simon Langton','B00364K6YW');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('John Grisham','0440245915');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Joel Schumacher','B0019NG7GI');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Harper Lee','0061743526');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Robert Mulligan','0783225857');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Harris, Thomas','0312195265');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Jonathan Demme','B000MGB6N2');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Jon Krakauer','0307387178');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Sean Penn','B001GMH8SI');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Peter Jackson','B003TT2X6I');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Peter Jackson','B003TT2X6S');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Brown, Dan','0307474275');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Ron Howard','B000I2J2XG');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Ron Howard','B002O5M4SU');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Tom Clancy','0425240339');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('John McTiernan','B001AII4SQ');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('James Patterson','0446692638');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Lee Tamahori','B00003CXUY');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('J. R. R. Tolkien','0618002251');

INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Robert Mulligan', 'Z783225857');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Lee Tamahori', 'Z00003CXUY');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Ron Howard', 'Z000I2J2XG');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Jonathan Demme', 'Z000MGB6N2');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Joel Schumacher', 'Z0019NG7GI');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('John McTiernan', 'Z001AII4SQ');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Sean Penn', 'Z001GMH8SI');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Ron Howard', 'Z002O5M4SU');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Simon Langton', 'Z00364K6YW');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Peter Jackson', 'Z003TT2X6I');
INSERT INTO `onlinebookstore`.`created_by` (name,ID) VALUES ('Peter Jackson', 'Z003TT2X6S');